.github/actions/setup/action.yml, package.json
Enable npm provenance
Confirmed it working here:
https://www.npmjs.com/package/npm-provenance-test2?activeTab=versions
=> Enable npm provenance

.changeset/mighty-eggs-report.md, .changeset/thick-yaks-rhyme.md, package.json, project.json
- Fix the CLI which is pointing to dist folder file.
=> fix: package missing dist folder

.gitignore, README.md, yarn.lock
=> chore: readme changes

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, src/create.ts, src/utils/templates.ts, yarn.lock
More docs polishing on how to Develop on BOA.
=> docs: polished the Develop section

.changeset/little-buttons-fetch.md, CHANGELOG.md
=> chore: release v0.2.0 ⚡

LICENSE.md, README.md
Added community section and refined README.md
=> docs: added community section and refined README.md

README.md
Trying out a new gif for the readme.
=> docs: updated readme gif

README.md
Now Alvaro has Twitter as well :)
=> docs: added Alvaro twitter contact

templates/buy-me-a-coffee-app/.eslintrc.js, templates/buy-me-a-coffee-app/package.json, templates/buy-me-a-coffee-app/src/components/Header.tsx, templates/buy-me-a-coffee-app/src/features/BuyMeACoffee/components/FormBuyCoffee.tsx, templates/buy-me-a-coffee-app/src/features/BuyMeACoffee/components/MemoCard.tsx, templates/buy-me-a-coffee-app/src/features/BuyMeACoffee/components/Memos.tsx, templates/buy-me-a-coffee-app/src/features/BuyMeACoffee/hooks/useBuyMeACoffeeMemos.ts, templates/buy-me-a-coffee-app/src/pages/_app.tsx, templates/buy-me-a-coffee-app/src/pages/index.tsx, templates/buy-me-a-coffee-app/yarn.lock
Alright, now the code is going to be 10x easier to read.
=> feat: added some nice Linting for import/order

.changeset/metal-feet-buy.md, README.md, templates/buy-me-a-coffee-app/package.json, templates/buy-me-a-coffee-app/src/components/Header.tsx, templates/buy-me-a-coffee-app/src/onchain/OnchainProviders.tsx, templates/buy-me-a-coffee-app/src/onchain/components/AccountConnectButton.tsx, templates/buy-me-a-coffee-app/src/onchain/components/index.tsx, templates/buy-me-a-coffee-app/src/pages/_app.tsx
In this PR we:
- **feat**: replaced RainbowKit with Coinbase Wallet SDK 💙
- **feat**: started shaping `AccountConnectButton` onchain component
=> feat: replaced Rainbowkit with CB Wallet SDK

.changeset/heavy-ducks-buy.md, CHANGELOG.md, templates/buy-me-a-coffee-app/src/pages/_app.tsx, templates/buy-me-a-coffee-app/src/pages/home/components/Memos.tsx
Time to flip the order of coffee
=> feat: reversed the memos order

README.md
Let's make the README easier to follow.
=> docs: nice and simple

.changeset/fifty-suits-retire.md, CHANGELOG.md, CONTRIBUTING.md, apps/build-onchain-apps/README.md, apps/build-onchain-apps/src/components/ThemesHeader.tsx, apps/build-onchain-apps/src/pages/home/index.tsx
=> docs: polish README

README.md
=> docs: added colors

.changeset/slow-experts-cover.md, .changeset/smooth-onions-enjoy.md
=> docs: small polish

README.md, package.json, project.json, tsconfig.json, vite.config.ts
=> feat: @coinbase/build-onchain-apps

.changeset/stupid-hats-roll.md
=> feat: bump version

CONTRIBUTING.md, README.md, apps/build-onchain-apps/src/components/ThemesHeader.tsx, apps/build-onchain-apps/src/components/TitleAndMetaTags.tsx, src/create.ts, src/utils/apps.ts
=> feat: more README polish

.changeset/tasty-moose-burn.md, CHANGELOG.md, README.md, apps/build-onchain-apps/README.md, apps/build-onchain-apps/src/components/TitleAndMetaTags.tsx, src/create.ts, src/utils/apps.ts
=> docs: onchain app is now lowercase

.changeset/grumpy-bobcats-wave.md, apps/build-onchain-apps/.gitignore, apps/build-onchain-apps/next.config.js, apps/build-onchain-apps/package.json, apps/build-onchain-apps/public/manifest.json, apps/build-onchain-apps/src/onchain/OnchainProviders.tsx, apps/build-onchain-apps/src/pages/_document.tsx, apps/build-onchain-apps/src/pages/home/index.tsx, apps/build-onchain-apps/tsconfig.json, apps/build-onchain-apps/yarn.lock
Converted App into PWA with `next-pwa`.
=> feat: Support for PWA

.changeset/grumpy-bobcats-wave.md, README.md
=> fix: release

apps/build-onchain-apps/package.json, apps/build-onchain-apps/src/components/Header.tsx, apps/build-onchain-apps/src/components/Navbar.module.css, apps/build-onchain-apps/src/components/Navbar.tsx, apps/build-onchain-apps/src/hooks/useActiveLink.ts, apps/build-onchain-apps/src/pages/home/index.tsx, apps/build-onchain-apps/yarn.lock
* Create Navbar component using `@radix-ui/react-navigation-menu`
* Local review with `yarn dev` and `yarn build`
=> Create Navbar component

apps/build-onchain-apps/src/components/Header.tsx, apps/build-onchain-apps/src/components/Navbar.module.css, apps/build-onchain-apps/src/global.css, apps/build-onchain-apps/src/pages/home/index.tsx
* Update Navbar styles and move it into the Header
* Local review
=> feat: Update Navbar styles and move it into the Header

apps/build-onchain-apps/yarn.lock, yarn.lock
* Regenerate yarn.lock files to correct registries
* Local review
=> fix: Regenerate yarn.lock files

.changeset/silly-ads-sit.md, CHANGELOG.md, README.md, apps/build-onchain-apps/package.json, apps/build-onchain-apps/yarn.lock
Measuring Web Performance is one of my favorite things ✨
Let's start add all the right libraries to capture the web insights we need to make an onchain app super fast.
=> feat: Init support Web Vitals with the Perfume.js library

.changeset/silly-ads-sit.md, .changeset/weak-rats-smash.md
=> chore: updated changeset

package.json
For Yarn v4, keep following the migrations steps https://yarnpkg.com/migration/guide
=> fix: Github Actions

apps/build-onchain-apps/jest.config.js, apps/build-onchain-apps/package.json, apps/build-onchain-apps/tsconfig.json, apps/build-onchain-apps/yarn.lock
To help measure web vitals and client analytics within Critical User Journey, we added an OSS library that helps using library like Google Analtyics and your favorite provider.
=> feat: added client-analytics package

.gitmodules, README.md, apps/build-onchain-apps/contracts/README.md, apps/build-onchain-apps/contracts/remappings.txt, apps/build-onchain-apps/contracts/script/CustomERC1155.s.sol, apps/build-onchain-apps/contracts/src/CustomERC1155.sol, apps/build-onchain-apps/contracts/test/CustomERC1155.t.sol
- Added OpenZeppelin and ERC1155
- Updated develop instructions
- Same Contract code as our mint page
Unit tests
=> [feat]  Added ERC1155 contracts 

.github/workflows/node.js.yml, apps/build-onchain-apps/package.json, apps/build-onchain-apps/src/components/Header.tsx, apps/build-onchain-apps/src/onchain/hooks/useOnchainCoffeeMemos.ts, apps/build-onchain-apps/src/onchain/utils/balance.test.ts, apps/build-onchain-apps/src/utils/timestamp.test.ts, apps/build-onchain-apps/tsconfig.json, apps/build-onchain-apps/yarn.lock
Made a few changes so types, tests and lint get back to work.
=> fix: types, tests, lint

apps/build-onchain-apps/tsconfig.json
Did some extra research, and es2020 is the best target for now.
https://caniuse.com/?feats=mdn-javascript_operators_optional_chaining,mdn-javascript_operators_nullish_coalescing,mdn-javascript_builtins_globalthis,es6-module-dynamic-import,bigint,mdn-javascript_builtins_promise_allsettled,mdn-javascript_builtins_string_matchall,mdn-javascript_statements_export_namespace,mdn-javascript_operators_import_meta
=> feat: es2020

.gitmodules, README.md, apps/build-onchain-apps/contracts/.env.example, apps/build-onchain-apps/contracts/.gitignore, apps/build-onchain-apps/contracts/README.md, apps/build-onchain-apps/contracts/remappings.txt
=> [chore] Easier instructions and setup

apps/build-onchain-apps/src/components/Header.tsx, apps/build-onchain-apps/src/components/MobileMenu.tsx, apps/build-onchain-apps/src/pages/_app.tsx
Implement drawer menu + hamburger icon for mobile screens. Implementation is based on [Radix's own website](https://github.com/radix-ui/website).
- https://github.com/radix-ui/website/blob/main/components/MobileMenu.tsx
Here's a demo video.
https://github.com/coinbase/build-onchain-apps/assets/43140758/5ff3f4e0-8763-48d0-afef-2ad66ef3b5a3
Locally.
=> feat: mobile menu

apps/build-onchain-apps/next.config.js, apps/build-onchain-apps/src/onchain/utils/balance.test.ts, apps/build-onchain-apps/src/pages/mint/components/Mint.tsx
I was testing a bit the Mint page, and the `<Image>` component was not well used.
=> fix: next image usage

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
I was trying to use our own Bug and Feature report system, and I got a bit annoyed on how many questions was asking.
It felt extra friction is not really need it now.
=> chore: making a bit easier reporting a bug

.changeset/selfish-hotels-tap.md, CHANGELOG.md, README.md
=> chore: changeset

apps/build-onchain-apps/jest.setup.ts, apps/build-onchain-apps/src/components/Navbar.tsx, apps/build-onchain-apps/src/hooks/useActiveLink.test.ts, apps/build-onchain-apps/src/hooks/useActiveLink.ts, apps/build-onchain-apps/src/utils/analytics.test.ts, apps/build-onchain-apps/src/utils/analytics.ts
=> chore: more tests

.github/workflows/foundry.yml
=> fix: enable Foundry github workflow

.github/workflows/release.yml
=> fix: release steps

apps/build-onchain-apps/src/providers/OnchainProviders.tsx, apps/build-onchain-apps/src/utils/chainConfiguration.test.ts, apps/build-onchain-apps/src/utils/chainConfiguration.ts
Shift from Goerli to Base for Production and Staging
Tested locally
=> [chore] Change from Goerli to Base for Production and Staging

apps/build-onchain-apps/src/contract/ContractSpecification.ts
Adding some types and a config file that will make it easier for us to support multiple chains. Pushing this up before any further implementation to get feedback on the approach taken here.
=> feat: basic multichain config

.changeset/neat-worms-bake.md
=> chore: changeset for v0.13

apps/build-onchain-apps/src/components/buy-me-coffee/ContractDemo.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/FormBuyCoffee.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/MemoCard.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/Memos.tsx, apps/build-onchain-apps/src/components/mint/SwitchNetwork.tsx, apps/build-onchain-apps/src/onchain/AccountConnectButton.tsx, apps/build-onchain-apps/src/providers/OnchainProviders.tsx
Removed `walletConnectWallet` as was adding CSS prefix at the top of the HTML element, which honestly is not a nice approach. Also, I am replacing Radix layout components with Tailwind, as I want us to be more clean in where and how to use Radix, as tailwind is going to be our main CSS solution.
Before
After
=> fix: removed extra CSS prefix

apps/build-onchain-apps/.eslintrc.js, apps/build-onchain-apps/src/components/buy-me-coffee/ContractDemo.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/FormBuyCoffee.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/MemoCard.tsx, apps/build-onchain-apps/src/components/mint/ContractDemo.tsx, apps/build-onchain-apps/src/components/mint/NotConnected.tsx, apps/build-onchain-apps/src/components/mint/SwitchNetwork.tsx, apps/build-onchain-apps/src/onchain/AccountConnectButton.tsx
=> fix: removed Text Radix in favor of Tailwind

apps/build-onchain-apps/src/components/home/Home.module.css, apps/build-onchain-apps/src/components/home/HomeHeader.tsx
Having some fun with CSS animation
https://github.com/coinbase/build-onchain-apps/assets/829214/6421257f-434c-4ca1-b1f7-d8518d1c2885
=> feat: added animated boat ⛵️

apps/build-onchain-apps/src/components/buy-me-coffee/ContractDemo.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/FormBuyCoffee.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/MemoCard.tsx, apps/build-onchain-apps/src/components/header/Menu.tsx, apps/build-onchain-apps/src/components/mint/ContractDemo.tsx, apps/build-onchain-apps/src/onchain/AccountConnectButton.tsx, apps/build-onchain-apps/tailwind.config.ts
Working with Tailwind is actually 10x easier to debug compared on just using Radix.
It's a bit saying, with Radix you can code faster, but as soon there is one little thing you want to change, than it's start getting a bit hard to debug and change.
I believe a pure Tailwind approach it's a more reliable way to promote apps that need to learn less tools to use and also have more support in how to fix and maintaining them.
=> fix: moved more Radix to Tailwind

apps/build-onchain-apps/package.json, apps/build-onchain-apps/pages/_app.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/FormBuyCoffee.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/MemoCard.tsx, apps/build-onchain-apps/src/components/mint/ContractDemo.tsx, apps/build-onchain-apps/src/components/mint/SwitchNetwork.tsx, apps/build-onchain-apps/src/global.css, apps/build-onchain-apps/src/onchain/AccountConnectButton.tsx, apps/build-onchain-apps/yarn.lock
Continuing to take Radix out of the equation
=> fix: removing more parts of Radix

README.md, apps/build-onchain-apps/src/components/home/Home.module.css
=> fix: wave css

.gitmodules, README.md, apps/build-onchain-apps/contracts/.gitignore, apps/build-onchain-apps/contracts/README.md, apps/build-onchain-apps/contracts/script/CustomERC1155.s.sol, apps/build-onchain-apps/contracts/src/BuyMeACoffee.sol, apps/build-onchain-apps/contracts/src/CustomERC1155.sol, apps/build-onchain-apps/contracts/test/BuyMeACoffee.t.sol, apps/build-onchain-apps/contracts/test/CustomERC1155.t.sol, src/create.ts
- Removes all warnings on build
- Adds clearer instructions on deploying your contract, creating an abi etc
- Adds a console.log to let the user know that contracts are loading when the user runs `npx @coinbase/build-onchain-apps@latest create`
- Formatted all contracts
=> [fix] Optimize instructions based on feedback for contracts

apps/build-onchain-apps/contracts/README.md, apps/build-onchain-apps/pages/api/chain/currentBlockNumber.test.ts, apps/build-onchain-apps/pages/api/chain/currentBlockNumber.ts, apps/build-onchain-apps/pages/api/mint/signature/free.test.ts, apps/build-onchain-apps/pages/api/mint/signature/free.ts, apps/build-onchain-apps/src/components/CodeBlock/CodeBlock.tsx, apps/build-onchain-apps/src/utils/chainConfiguration.ts, apps/build-onchain-apps/src/utils/configuration.ts
=> fix: format

apps/build-onchain-apps/pages/_document.tsx, apps/build-onchain-apps/src/global.css
Added both Roboto Mono and Inter as our main Google fonts.
=> feat: introducing the Roboto Mono and Inter fonts

apps/build-onchain-apps/package.json, apps/build-onchain-apps/src/components/header/Header.tsx, apps/build-onchain-apps/src/components/header/Menu.tsx, apps/build-onchain-apps/src/components/header/Navbar.tsx, apps/build-onchain-apps/src/components/home/HomeHeader.tsx, apps/build-onchain-apps/src/utils/classNames.test.ts, apps/build-onchain-apps/src/utils/classNames.ts, apps/build-onchain-apps/tailwind.config.ts, apps/build-onchain-apps/yarn.lock
In this PR we replace our custom `classNames` utils with something a bit more industry standard with the `clsx` library. 
=> feat: replaced classNames with clsx

apps/build-onchain-apps/package.json, apps/build-onchain-apps/prettier.config.js, apps/build-onchain-apps/src/components/header/Navbar.tsx, apps/build-onchain-apps/yarn.lock
So apparently Radix primitives are quite dope!
We are going to use `@radix-ui/react-navigation-menu` for the menu of all the experiences.
=> feat: added Radix navigation menu primitives for Experiences menu

apps/build-onchain-apps/.eslintrc.js, apps/build-onchain-apps/pages/api/mint/signature/free.test.ts, apps/build-onchain-apps/pages/api/mint/signature/free.ts, apps/build-onchain-apps/pages/home/index.tsx, apps/build-onchain-apps/src/components/CodeBlock/CodeBlock.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/FormBuyCoffee.tsx, apps/build-onchain-apps/src/components/header/Menu.tsx, apps/build-onchain-apps/src/components/header/Navbar.tsx, apps/build-onchain-apps/src/components/header/NavbarMobile.tsx, apps/build-onchain-apps/src/components/mint/ContractDemo.tsx, apps/build-onchain-apps/src/components/mint/SignatureMint.tsx, apps/build-onchain-apps/src/components/mint/SwitchNetwork.tsx, apps/build-onchain-apps/src/contract/ContractSpecification.test.ts, apps/build-onchain-apps/src/hooks/useActiveLink.ts, apps/build-onchain-apps/src/hooks/useBlockNumber.test.ts, apps/build-onchain-apps/src/hooks/useOnchainCoffeeMemos.ts, apps/build-onchain-apps/src/providers/OnchainProviders.tsx, apps/build-onchain-apps/src/utils/chainConfiguration.test.ts, apps/build-onchain-apps/src/utils/chainConfiguration.ts, apps/build-onchain-apps/src/utils/provider.ts
=> feat: added alphabetize import-order

apps/build-onchain-apps/onchainKit/AccountConnectButton.tsx, apps/build-onchain-apps/onchainKit/components/OnchainAvatar.tsx, apps/build-onchain-apps/src/components/header/Header.module.css, apps/build-onchain-apps/src/components/header/Navbar.tsx, apps/build-onchain-apps/src/components/home/Guide.tsx, apps/build-onchain-apps/src/global.css, apps/build-onchain-apps/src/utils/chainConfiguration.test.ts, apps/build-onchain-apps/src/utils/chainConfiguration.ts
In this PR we have fun by:
- starting coding the `OnchainAvatar` component
- adding some animation on the Navbar
- polish the CSS in the navbar
- fixing the `get-started` anchor scroll
- added `mainet` as supported chain
=> feat: init OnchainAvatar

apps/build-onchain-apps/onchainKit/AccountConnectButton.tsx, apps/build-onchain-apps/onchainKit/components/OnchainAvatar.tsx, apps/build-onchain-apps/src/components/header/Header.tsx, apps/build-onchain-apps/src/components/header/Menu.tsx, apps/build-onchain-apps/src/components/header/Navbar.tsx
Fix some UI jank.
_PS: ENS Avatars are not working for me._
https://github.com/coinbase/build-onchain-apps/assets/43140758/c4b262a8-8fdb-4d2c-9773-027e2ede7377
https://github.com/coinbase/build-onchain-apps/assets/43140758/66ebb00c-5b7b-4d9e-81d9-844a961e0614
Locally.
=> fix: header jank

.gitmodules, apps/build-onchain-apps/src/hooks/contracts.ts
Migrating contracts to base sepolia
=> chore: Migrate to base sepolia

apps/build-onchain-apps/app/buy-me-coffee/page.tsx, apps/build-onchain-apps/app/layout.tsx, apps/build-onchain-apps/app/mint/page.tsx, apps/build-onchain-apps/app/page.tsx, apps/build-onchain-apps/app/signature-mint/page.tsx
=> Add a comment to explain the new app folder pattern

apps/build-onchain-apps/onchainKit/AccountConnectButton.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/FormBuyCoffee.tsx, apps/build-onchain-apps/src/components/buy-me-coffee/MemoCard.tsx, apps/build-onchain-apps/src/components/footer/Footer.tsx, apps/build-onchain-apps/src/components/header/Header.tsx, apps/build-onchain-apps/src/components/header/Menu.tsx, apps/build-onchain-apps/src/components/header/Navbar.tsx, apps/build-onchain-apps/src/components/home/Guide.tsx, apps/build-onchain-apps/src/components/home/WhyUseIt.tsx, apps/build-onchain-apps/src/components/mint/SignatureMint.tsx, apps/build-onchain-apps/tailwind.config.ts
Small follow up of #235 
N/A
Locally.
=> feat: custom BOAT tailwind colors for footer

apps/build-onchain-apps/package.json, apps/build-onchain-apps/src/hooks/contracts.test.ts, apps/build-onchain-apps/src/hooks/contracts.ts, apps/build-onchain-apps/src/hooks/useBlockNumber.ts
Added a few extra tests so we make sure the right contracts are in place and the local build apparently was not able to pull the Google Fonts correctly. Clean up the `.next` folder fix the issue.
=> chore: tests and local build

apps/build-onchain-apps/.stylelintrc.json, apps/build-onchain-apps/package.json, apps/build-onchain-apps/src/components/CodeBlock/CodeBlock.module.css, apps/build-onchain-apps/src/components/home/Home.module.css, apps/build-onchain-apps/src/global.css, apps/build-onchain-apps/yarn.lock
In this PR we fix Rainbowkit CSS and upgrade all major libraries.
=> fix: rainbowkit css

apps/build-onchain-apps/onchainKit/components/OnchainAddress.tsx, apps/build-onchain-apps/onchainKit/components/OnchainAvatar.tsx, apps/build-onchain-apps/onchainKit/hooks/useBlockExplorerLink.test.ts, apps/build-onchain-apps/onchainKit/hooks/useBlockExplorerLink.ts, apps/build-onchain-apps/onchainKit/hooks/useCollectionMetadata.ts, apps/build-onchain-apps/onchainKit/hooks/useEnsAvatar.ts, apps/build-onchain-apps/onchainKit/hooks/useEnsName.ts, apps/build-onchain-apps/onchainKit/index.ts, apps/build-onchain-apps/onchainKit/utils/address.ts, apps/build-onchain-apps/onchainKit/utils/index.ts, apps/build-onchain-apps/package.json, apps/build-onchain-apps/src/components/header/AccountConnect.tsx, apps/build-onchain-apps/src/components/header/AccountDropdown.tsx, apps/build-onchain-apps/src/components/header/Header.tsx, apps/build-onchain-apps/src/components/header/Menu.tsx, apps/build-onchain-apps/src/components/mint/ContractDemo.tsx, apps/build-onchain-apps/src/components/mint/SignatureMint.tsx, apps/build-onchain-apps/yarn.lock
This PR has some cool stuff:
- we define a basic `OnchainAddress` component
- we allow `OnchainAvatar` to have `className` customizable
- we make OnchainKit folder behave more like a library
- oh yeah we use `@radix-ui/react-dropdown-menu` to have a dope dropdown.
=> feat: added Account Dropdown

apps/build-onchain-apps/tailwind.config.ts
=> fix: tailwind

template/contracts/README.md
=> chore: format readme

.github/workflows/foundry.yml
Updating the CI for foundry based on the folder structure change
=> fix: Fix CI for Foundry

template/next.config.js
Removing contracts from next build
=> fix: Remove contracts from next build

template/next.config.js, template/tsconfig.json
=> fix: build

src/utils/git.ts
=> fix: Remove template from submodule

README.md
Did some polish after a few folks sharing private feedback on our README.
=> docs: some README polish

template/app/frame/page.tsx, template/onchainKit/core/generateFrameMetadata.ts, template/onchainKit/core/generateFrameNextMetadata.ts, template/onchainKit/core/index.ts
=> feat: Farcaster Frame LFG Part III

template/app/api/frame/route.ts, template/app/frame/page.tsx
=> feat: Farcaster Frame LFG Part IV

README.md
=> Remove web3 from README.md

template/app/api/frame/route.ts, template/package.json, template/yarn.lock
=> feat: using `getFrameAccountAddress` from `@coinbase/onchainkit`

template/app/api/frame/route.ts, template/package.json, template/yarn.lock
=> chore: test latest kit

README.md
=> fix: update the forge script in readme

template/app/api/frame/route.ts, template/app/frame/page.tsx, template/package.json, template/yarn.lock
=> chore: latest kit

template/src/components/footer/Footer.tsx
=> Add some footer styles

template/jest.config.js, template/src/components/code-block/CodeBlock.test.tsx
=> chore: add tests

template/app/api/frame/route.ts, template/package.json, template/yarn.lock
=> feat: latest kit 0.3.1

template/src/pageComponents/home/Guide.tsx, template/src/pageComponents/signature-mint/Guide.tsx
cleaning up the guide instructions
=> fix: minor bugs in guide

template/src/pageComponents/buy-me-coffee/ContractDemo.tsx, template/src/pageComponents/buy-me-coffee/steps/BuyCoffeeFormStep/FormBuyCoffee.tsx, template/src/pageComponents/buy-me-coffee/steps/OutOfGasStep/OutOfGasStep.tsx, template/yarn.lock
- Added state for Out of Gas
- Added state trigger in error callback
**Screenshots**
_Out of Gas View_
- Locally
=> feat: Buy Me a Coffee - Out of Gas State

template/contracts/src/BuyMeACoffee.sol, template/contracts/test/BuyMeACoffee.t.sol, template/src/contract/BuyMeACoffee.ts, template/src/hooks/contracts.test.ts, template/src/hooks/contracts.ts
Adding the cost check in the contract itself
=> fix: Check cost of coffee in the contract

template/src/components/code-block/CodeBlock.test.tsx, template/src/components/code-block/CodeBlock.tsx
=> fix: use async Server Component in <CodeBlock />

template/app/api/frame/route.ts, template/package.json, template/yarn.lock
=> feat: latest kit

template/src/components/NextImage/NextImage.tsx, template/src/components/ProgressBar/ProgressBar.tsx, template/src/pageComponents/mint/ContractDemo.tsx
- Improved Mint NFT page
- Bring Mint NFT page up to Figma spec
- Add common components for NextImage and ProgressBar
**Screenshots:**
_Desktop_
_Tablet_
_Mobile_
- Locally
=> feat: Mint NFT UI

template/src/components/header/__tests__/Navbar.test.tsx, template/src/hooks/useOnchainCoffeeMemos.test.tsx, template/src/hooks/useOnchainCoffeeMemos.ts, template/src/pageComponents/buy-me-coffee/ContractDemo.test.tsx, template/src/pageComponents/signature-mint/ContractDemo.test.tsx
- refactor some existing hooks 
- add tests
Unit tests
=> chore: refactor, add tests

template/src/components/code-block/CodeBlock.test.tsx, template/src/components/code-block/CodeBlock.tsx
Reverts coinbase/build-onchain-apps#308
=> Revert "fix: use async Server Component in <CodeBlock />"

template/package.json, template/src/components/header/AccountConnect.tsx, template/src/components/header/AccountDropdown.tsx, template/src/components/header/AccountInfoPanel.tsx, template/src/components/header/Header.tsx, template/src/components/header/Menu.tsx, template/src/components/header/Navbar.tsx, template/src/components/header/NavbarMobile.tsx, template/src/components/header/__tests__/Navbar.test.tsx, template/src/components/header/__tests__/NavbarMobile.test.tsx, template/yarn.lock
Manual + Unit tests
|Before|After|
|---|---|
|<img width="1792" alt="Screenshot 2024-02-07 at 10 51 55 AM" src="https://github.com/coinbase/build-onchain-apps/assets/9765685/fec58593-5f0f-47cc-9686-79f666ef925a">|<img width="1789" alt="Screenshot 2024-02-07 at 10 53 24 AM" src="https://github.com/coinbase/build-onchain-apps/assets/9765685/9ed554c2-02da-4486-9884-bed3af027afe">|
|<img width="319" alt="Screenshot 2024-02-07 at 10 54 18 AM" src="https://github.com/coinbase/build-onchain-apps/assets/9765685/41eed237-61b6-449e-87f0-f68585e9650a">|<img width="321" alt="Screenshot 2024-02-07 at 10 54 46 AM" src="https://github.com/coinbase/build-onchain-apps/assets/9765685/ba2e8c64-037c-4bf9-a49b-59b3d7b60abb"><img …
=> feat: add mobile navbar

template/onchainKit/hooks/useBlockExplorerLink.test.ts, template/onchainKit/hooks/useCollectionMetadata.ts, template/package.json, template/src/hooks/contracts.test.ts, template/src/hooks/contracts.ts, template/src/hooks/useBlockNumber.test.ts, template/src/hooks/useBlockNumber.ts, template/src/hooks/useOnchainCoffeeMemos.test.tsx, template/src/hooks/useOnchainCoffeeMemos.ts, template/src/pageComponents/buy-me-coffee/steps/BuyCoffeeFormStep/FormBuyCoffee.tsx, template/src/pageComponents/mint/ContractDemo.tsx, template/src/pageComponents/mint/SwitchNetwork.tsx, template/src/pageComponents/mint/steps/StartMintStep.tsx, template/src/pageComponents/signature-mint/ContractDemo.tsx, template/src/providers/OnchainProviders.tsx, template/src/store/supportedChains.ts, template/yarn.lock
=> chore: update to onchainkit@0.5.1, viem@2, wagmi@2

README.md, template/README.md, template/src/pageComponents/home/Guide.tsx, template/src/providers/OnchainProviders.tsx
- sync getting started docs across multiple locations
- update error message to be clearer on how to resolve the error
locally
=> chore: update docs

template/src/hooks/useOnchainCoffeeMemos.ts, template/src/pageComponents/buy-me-coffee/ContractDemo.tsx, template/src/pageComponents/buy-me-coffee/steps/BuyCoffeeFormStep/FormBuyCoffee.tsx
- Fixing refetch of any new coffees
- Fixing when the form is disabled
- Fixing success and error states
=> fix: minor bugs on buy-me-coffee

template/src/components/Button/Button.test.tsx, template/src/components/ProgressBar/ProgressBar.test.tsx, template/src/components/ProgressBar/ProgressBar.tsx, template/src/components/banner/banner.test.tsx
* Adds `<Banner/>` test cases
* Adds `<ProgressBar/>` test cases
* Adds `<Button/>` test cases
NA
`yarn test`
=> test: add reusable components unit tests

template/package.json, template/yarn.lock
=> chore: updated OnchainKit to v0.6.1

template/src/hooks/useOnchainCoffeeMemos.ts, template/src/pageComponents/buy-me-coffee/ContractDemo.tsx, template/src/pageComponents/buy-me-coffee/steps/BuyCoffeeFormStep/FormBuyCoffee.tsx
Reverts coinbase/build-onchain-apps#341
=> fix: Revert "fix: minor bugs on buy-me-coffee"

.github/workflows/app-build.js.yml, .github/workflows/app-lint.js.yml, .github/workflows/app-styles.js.yml, .github/workflows/app-test.js.yml, README.md, template/README.md, template/package.json, template/src/pageComponents/home/Guide.tsx, template/yarn.lock
This reverts stuff from https://github.com/coinbase/build-onchain-apps/pull/340
=> docs: cleanup and better CI

template/src/components/Button/Button.test.tsx, template/src/components/ProgressBar/ProgressBar.test.tsx, template/src/components/ProgressBar/ProgressBar.tsx, template/src/components/banner/banner.test.tsx
Adding back https://github.com/coinbase/build-onchain-apps/pull/322
=> chore: adding back some tests

template/src/providers/OnchainProviders.tsx
Checking is configuring connectors manually fixes the issue
=> fix: Manually configure connectors

template/src/components/header/AccountInfoPanel.tsx, template/src/components/header/Header.tsx, template/src/components/header/Navbar.test.tsx, template/src/components/header/Navbar.tsx, template/src/components/header/NavbarMobile.test.tsx, template/src/components/header/NavbarMobile.tsx
Follow-up on comments from PR #329 
=> chore: cleanup header, Navbar

README.md, src/utils/apps.ts, template/web/src/pageComponents/home/Guide.tsx
Updating instructions for new folder structure
=> fix:  instructions based on the new folder structure

.changeset/green-kangaroos-nail.md, src/create.ts, src/utils/apps.ts, template/package.json
Adding changeset and package.json
=> fix: Add package.json to template folder

template/web/src/providers/OnchainProviders.tsx, template/web/src/store/createWagmiConfig.test.ts, template/web/src/store/createWagmiConfig.ts, template/web/src/store/supportedChains.test.ts, template/web/src/store/supportedChains.ts
=> fix: use supported chains by env

template/web/app/buy-me-coffee/index.tsx, template/web/src/components/header/NavbarMobile.tsx, template/web/src/components/horizontal-line/HorizontalLine.tsx, template/web/src/pageComponents/buy-me-coffee/MemoCard.tsx, template/web/src/pageComponents/buy-me-coffee/Profile.tsx
=> fix: minor layout fixes

.gitmodules
- ignore gitmodules by setting ignore to dirty [official docs](https://git-scm.com/docs/gitmodules#Documentation/gitmodules.txt-dirty)
locally
=> [feature] faster git status

template/web/app/buy-me-coffee/_components/ContractAlert.tsx, template/web/app/buy-me-coffee/_components/ContractDemo.tsx, template/web/app/buy-me-coffee/_components/FormBuyCoffee.tsx, template/web/app/buy-me-coffee/_components/InputText.tsx, template/web/app/buy-me-coffee/_components/Label.tsx, template/web/app/buy-me-coffee/_components/TextArea.tsx, template/web/app/buy-me-coffee/_components/TransactionSteps.tsx, template/web/app/buy-me-coffee/_components/useSmartContractForms.ts, template/web/app/buy-me-coffee/_hooks/useFields.ts, template/web/app/buy-me-coffee/_hooks/useOnchainCoffeeMemos.ts
Two main files to look at:
- `template/web/app/buy-me-coffee/_components/FormBuyCoffee.tsx`
- `template/web/app/buy-me-coffee/_components/useSmartContractForms.ts`
I attempted to make buy-me-coffee form as generic as possible. 
locally
=> [chore] refactor buymecoffee forms

.changeset/sour-planets-protect.md
=> chore: prep release

src/create/getUserInput.ts
update basescan env var length to 34
=> [chore] update basescan env var length to 34

README.md, template/web/app/home/_components/WhyUseIt.tsx, tsconfig.json
=> docs: README cleanup

template/web/app/home/_components/Guide.tsx, template/web/app/mint/_components/Guide.tsx
=> feat: update side nav feels

template/web/app/mint/_components/Guide.tsx
=> chore: complete Guide for /mint

template/web/app/buy-me-coffee/_components/ContractAlert.tsx, template/web/app/mint/_components/ContractDemo.tsx, template/web/src/hooks/contracts.ts, template/web/src/hooks/test/contracts.test.ts
=> feat: read onchain data without connected wallet

src/create/getUserInput.ts
- select all experiences by default in cli create
locally
=> fix: select all experiences by default in cli create

template/web/app/buy-me-coffee/_components/Guide.tsx
=> chore: complete Guide for /buy-me-coffee

template/web/app/mint/_components/ContractDemo.tsx
=> feat: show NFT image without connected wallet

template/web/app/mint/_components/ContractDemo.tsx
=> fix: add 'Connect Wallet' button in not-connected state

template/web/app/fonts.ts, template/web/app/layout.tsx, template/web/app/paymaster-bundler/_components/Header.tsx, template/web/app/paymaster-bundler/_components/Vault.tsx
- Refactor fonts to separate file
- Use classname on Paymaster Bundler
- Locally
=> bug: Refactor Fonts and Fix on Paymaster Bundler

template/web/app/home/_components/Guide.tsx, template/web/app/home/_components/HomeHeader.tsx, template/web/app/home/_components/WhyUseIt.tsx, template/web/app/home/index.tsx, template/web/src/components/layout/footer/Footer.tsx, template/web/src/components/layout/footer/FooterIcon.tsx
Removed bunch of steps to reduce cognitive overload and encourage users to setup the repo.
Next PR will address other guides
locally
=> [chore] homepage touchup

template/web/app/buy-me-coffee/_components/ContractDemo.tsx, template/web/app/buy-me-coffee/_components/Guide.tsx, template/web/app/buy-me-coffee/index.tsx, template/web/app/home/_components/Guide.tsx, template/web/app/home/_components/WhyUseIt.tsx, template/web/app/layout.tsx, template/web/app/mint/_components/ContractDemo.tsx, template/web/app/mint/_components/Guide.tsx, template/web/app/mint/index.tsx, template/web/app/paymaster-bundler/_components/PaymasterBundlerDemo.tsx, template/web/app/paymaster-bundler/index.tsx, template/web/src/components/layout/Main.tsx, template/web/src/components/layout/banner/banner.tsx, template/web/src/components/layout/guide/A.tsx, template/web/src/components/layout/guide/H3.tsx, template/web/src/components/layout/guide/H4.tsx, template/web/src/components/layout/guide/Hr.tsx, template/web/src/components/layout/guide/P.tsx, template/web/src/components/layout/guide/Section.tsx, template/web/src/components/layout/guide/TableOfContents.tsx, template/web/src/components/layout/guide/index.ts, template/web/src/components/layout/guide/useGuideScroll.ts, template/web/src/components/layout/header/Navbar.tsx, template/web/src/components/layout/header/NavbarMobile.tsx
- add `useGuideScroll` to share scrolling behavior across all guides
- add various text components for guides
- sync layout for all experiences
- fix font. Now global font is `Inter`
locally
=> feat: sync all experiences with shared components

src/create/setupProject.ts
Remove metadata from root page when creating a blank app
locally
=> fix: cleaner blank app

src/create/setupProject.ts
=> fix git clone command

template/web/app/paymaster-bundler/page.tsx, template/web/src/components/layout/banner/banner.tsx
Adding a warning banner for all future use cases
=> Add WIP banner for Paymaster page

template/web/app/buy-me-coffee/layout.tsx, template/web/app/mint/layout.tsx, template/web/app/page.tsx, template/web/app/paymaster-bundler/layout.tsx, template/web/src/components/layout/footer/Footer.tsx, template/web/src/components/layout/header/Navbar.tsx
- Added page level titles and descriptions for SEO 🌐
- Improved A11y Lighthouse score by adding ariaLabels where needed 🚀
- Extended support for ariaLabel prop for NextLink component 🧩
✅ Tested locally
✅ Lighthouse chrome plugin
=> chore: SEO and a11y improvements

src/create/getUserInput.ts, src/create/setupProject.ts, template/web/src/components/layout/banner/banner.tsx, template/web/tailwind.config.ts
- Updating the banner to match the design Rose suggested
- Adding homepage if no experience is selected
=> fIx: warning banner and add home page when empty app selected

.changeset/quiet-turtles-vanish.md, src/create/setupProject.ts
On blank projects, remove experiences from the header
=> fix: On blank projects, remove experiences 

template/web/app/paymaster-bundler/_components/GamePlay.tsx, template/web/app/paymaster-bundler/_components/Vault.tsx
- Address design review feedback
- Basic text changes
- Locally
=> enhancements: Address Design Review Feedback for Paymaster Bundler

template/README.md, template/web/README.md
- add a root README file
- Add abi instructions to `web/` README
=> [chore] update docs

template/web/app/paymaster-bundler/_components/GamePlay.tsx, template/web/app/paymaster-bundler/_components/Guide.tsx, template/web/app/paymaster-bundler/_components/Header.tsx, template/web/app/paymaster-bundler/_components/PaymasterBundlerDemo.tsx, template/web/app/paymaster-bundler/_contracts/PaymasterBundlerABI.ts, template/web/app/paymaster-bundler/_contracts/usePaymasterBundlerContract.test.ts, template/web/app/paymaster-bundler/_contracts/usePaymasterBundlerContract.ts, template/web/app/paymaster-bundler/_utils/fetchNFTs.ts, template/web/app/paymaster-bundler/constants.ts, template/web/src/components/layout/guide/Li.tsx, template/web/src/components/layout/guide/Ul.tsx, template/web/src/components/layout/guide/index.ts
- Use generateContractHook for Paymaster Bundler
- Locally
=> enhancement: Use Hook for Paymaster Bundler Contract

template/web/src/components/layout/header/AccountDropdown.tsx, template/web/src/components/layout/header/AccountInfoPanel.tsx, template/web/src/components/layout/header/NavbarMobile.tsx
- fix alignment in both mobile and desktop navbars
locally
=> fix: align all navbars

template/web/app/paymaster-bundler/_components/Guide.tsx
=> chore: add copy for envars

template/web/package.json, template/web/yarn.lock
=> chore: latest OnchainKit

template/contracts/src/BuyMeACoffee.sol, template/contracts/test/BuyMeACoffee.t.sol
=> feat: polish Buy Me Coffee

README.md, src/create.ts, template/README.md, template/web/README.md, template/web/app/home/_components/HomeHeader.tsx, template/web/app/page.tsx, template/web/src/utils/test/generateMetadata.test.ts
=> feat: rebrand from Build Onchain App Toolkit to Build Onchain App Template

template/web/package.json, template/web/yarn.lock
=> chore: updated OnchainKit to v0.13.4

src/create.ts, src/create/getUserInput.ts, src/create/setupProject.ts, src/utils/apps.ts, template/web/package.json, template/web/src/OnchainProviders.tsx, template/web/src/store/createWagmiConfigWithRK.ts, template/web/yarn.lock
=> feat: adding Smart Wallet as choice into the CLI

src/create/setupProject.ts, template/web/app/home/_components/WhyUseIt.tsx, template/web/package.json, template/web/src/OnchainProviders.tsx, template/web/src/OnchainProvidersWithRK.tsx, template/web/src/components/layout/header/AccountConnect.tsx, template/web/src/store/createWagmiConfig.ts, template/web/src/store/test/createWagmiConfig.test.ts, template/web/yarn.lock
To test the CLI run `ts-node src/index.ts create` from root.
To test the app run `yarn dev` from `template/web`
=> feat: added Smart Wallet to BOAT

src/create/getUserInput.ts, template/web/README.md
update cdp links to include BOAT tracking
=> [trivial] update cdp links

.changeset/metal-berries-thank.md
add changeset for metrics tracking
=> chore: add changeset for metrics tracking

src/create/setupProject.ts
=> Fix setup error because of mistakes in file names

.changeset/great-garlics-judge.md, CHANGELOG.md, package.json
=> chore: version packages v0.28.1 🌊

.changeset/little-spies-watch.md, src/README.md, src/create/setupProject.ts, template/web/app/simple/HomePage.tsx, tsconfig.json
=> feat: started simple Homepage to showcase SW

.changeset/eight-roses-give.md
Minor release for updating the Paymaster Bundler experience to use the CDP paymaster. 
- Ran `yarn changeset`
=> Paymaster Bundler Smart Wallet release

template/web/app/paymaster-bundler/_components/PaymasterBundlerDemo.tsx, template/web/src/utils/paymasterClient.ts
Revert changes for: [Update Paymaster Env visibility #500](https://github.com/coinbase/build-onchain-apps/pull/500)
=> fix: Revert paymaster env changes 
