- .changeset/calm-clouds-roll.md
- package.json
- CLI bin path should point to dist folder.
> fix: CLI bin path

- README.md
- src/create.ts
- src/utils/dir.ts
Kept polishing the README, also made `/apps` as the location where templates are generated. This will make a bit more clean to generate different type of apps and have them all in the same folder.
> feat: moved templated created inside /apps

- .changeset/eighty-plants-eat.md
- apps/build-onchain-apps/package.json
- apps/build-onchain-apps/yarn.lock
Update three libraries that interact with `@ledgerhq/connect-kit`:
- `rainbowkit`: https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.3.1
- `wagmi`: https://github.com/wevm/wagmi/releases/tag/wagmi%401.4.12
- `viem`: https://github.com/wevm/viem/releases/tag/viem%401.19.15
Also locked the versions, so we reduce future surprises.
> fix: mitigate a supply-chain attack on the @ledgerhq/connect-kit package

- CODE_OF_CONDUCT.md
This corrects the documentation of where to report inappropriate behavior by directing people to the Base Discord.
> Update where to report inappropriate behavior

- apps/build-onchain-apps/package.json
- apps/build-onchain-apps/pages/api/README.md
- apps/build-onchain-apps/pages/api/chain/currentBlockNumber.test.ts
- apps/build-onchain-apps/pages/api/chain/currentBlockNumber.ts
- apps/build-onchain-apps/src/hooks/useBlockNumber.test.ts
- apps/build-onchain-apps/src/hooks/useBlockNumber.ts
- apps/build-onchain-apps/src/onchain/AccountConnectButton.tsx
- apps/build-onchain-apps/src/utils/provider.ts
Added a blockNumber api + react hook for the FE to consume from the BE API.
1. Added new API route  `/api/chain/currentBlockNumber?chainId=${chainId}`
2. Added a new reactHook useCurrentBlockNumber
1. Polls for the block number every 10 seconds by default
2. Added to the AccountConnectButton feature.
1. Why would we want blockNumber on the backend?
Sometimes it is helpful to get the block number from the backend to ensure the FE is in sync with network.  And mainly, that our FE And BE are in alignment.  Not the most critical feature, but this showcases how we would make a call to the BE from a react hook
2. Is interval the best idea in a react hook?
Probably not, we should implement a global state handler, will let some of react pros tackle …
> Adding Block Number API + React Hook

- apps/build-onchain-apps/contracts/src/BuyMeACoffee.sol
I've optimized the `buyCoffee` function for gas efficiency by changing string arguments to `calldata`. This change is aimed at reducing gas consumption during function execution without affecting its functionality.
- Please review the modifications made to the `buyCoffee` function and ensure that the changes align with gas efficiency goals.
I have tested the updated function locally to ensure that it still functions as expected. Additionally, gas profiling and benchmarking could be conducted to verify the gas savings.
> Optimize buyCoffee function for gas efficiency (calldata) 

- apps/build-onchain-apps/package.json
- apps/build-onchain-apps/src/components/CodeBlock/CodeBlock.module.css
- apps/build-onchain-apps/src/components/CodeBlock/CodeBlock.tsx
- apps/build-onchain-apps/src/components/home/Guide.tsx
- apps/build-onchain-apps/src/components/home/HomeHeader.tsx
- apps/build-onchain-apps/src/global.css
- apps/build-onchain-apps/src/onchain/AccountConnectButton.tsx
- apps/build-onchain-apps/tailwind.config.ts
- apps/build-onchain-apps/yarn.lock
This PR does some nice cleanup:
- now we use `shikiji` to auto generate style for our codeblocks. Btw the component needs more polishing but at least now there is some automated color.
- set `color-scheme: dark;` at root, so we get some nice browser automated css set.
- fix a weird horizontal scroll with `overflow-x: hidden;`
- used the latest design to customize the connect wallet button.
> feat: used shikiji for some dope CodeBlock

- apps/build-onchain-apps/src/components/header/Navbar.tsx
Removed unnecessary `originSite` that was causing this console error in the browser.
N/A
Locally
> fix: next link console error

- template/src/utils/generateMetadata.test.ts
- template/src/utils/generateMetadata.ts
Explicitly sets metadataBase to suppress build warnings. From: https://github.com/coinbase/build-onchain-apps/issues/257
Added a `BOAT_DEPLOY_URL` env var to set the metadataBase value for build/deploy, otherwise falls back to `VERCEL_URL` or `http://localhost:3000` locally
> fix: set metadataBase

- template/src/providers/OnchainProviders.tsx
Add support for using the user's preferred system theme (light/dark).
It's a jarring experience to open a big, white Connect modal when the system is set to dark theme.
Before (on dark mode)
After (on dark mode)
Set your OS to light mode -> see light theme
Set your OS to dark mode -> see dark theme
> chore: Support the user's system theme

- template/src/hooks/useUserCanAfford.test.ts
- template/src/hooks/useUserCanAfford.ts
- template/src/pageComponents/buy-me-coffee/FormBuyCoffee.tsx
- New utility for `useAddressCanAfford`
- New utility for `useLoggedInUserCanAfford`
- Unit tests for both
- Utilize above utilities to adjust UX if a user cannot afford to buy coffee
If a user  would be allowed to initiate a transaction, which would lead to a failure of transaction, without notifying the user
The UX adjusts accordingly
- Visit `/buy-me-coffee` with an account that has > 0.5ETH on Base Sepolia. User should be able to buy coffee
- Visit `/buy-me-coffee` with an account that has < 0.5ETH on Base Sepolia. User should **not** be able to buy coffee
> Utility to see if a user can afford amount + utilize in FormBuyCoffee

- template/src/components/banner/banner.tsx
- fixed banner component responsiveness  
| old | new |
|-----|-----|
|   ![CleanShot 2024-01-28 at 04 51 15@2x](https://github.com/coinbase/build-onchain-apps/assets/83667312/92cdc7f0-0e5c-49e4-a09f-792c5406f621)  |    ![CleanShot 2024-01-28 at 04 52 08@2x](https://github.com/coinbase/build-onchain-apps/assets/83667312/c35b4ed0-bf4c-4f53-b7b0-65d82d8e9eeb) |
|   ![CleanShot 2024-01-28 at 04 52 26@2x](https://github.com/coinbase/build-onchain-apps/assets/83667312/1602fe38-c770-48d6-b6f3-8f1c2f03f045)|    ![CleanShot 2024-01-28 at 04 52 47@2x](https://github.com/coinbase/build-onchain-apps/assets/83667312/687d697a-8a4d-437a-99c7-fbc62a6b6b00)|
> fix: banner component mobile view responsiveness

- yarn.lock
Affected of this project `coinbase/build-onchain-apps` are vulnerable to Improper Input Validation due to the improper handling of URLs by the `url.parse()` function. When new `URL()` throws an error, it can be manipulated to misinterpret the hostname. An attacker could exploit this weakness to redirect traffic to a malicious site, potentially leading to information disclosure, phishing attacks, or other security breaches.
**PoC:**
```js
let url = 'http://[localhost]/admin';
try{
new URL(url); // ERROR : Invalid URL
}catch{
url.parse(url); // -> http://localhost/admin
}
let url = 'http://attacker.domain*.allowed.domain:a';
try{
new URL(url); // ERROR : Invalid URL
}catch{
url.parse(url); // -> http://attacker.domain/*.allowed.domain:a
}
```
Below is part of `follow-redirects's` .js code. …
> Update and Patched Improper Input Validation improperly handles URLs in the url.parse() function

- template/src/pageComponents/mint/ContractDemo.tsx
- template/src/pageComponents/mint/steps/MintCompleteStep.tsx
- template/src/pageComponents/mint/steps/OutOfGasStep.tsx
- template/src/pageComponents/mint/steps/StartMintStep.tsx
- Error such as user rejecting a wallet popup was not resetting state back
- Incorrect condition was used to display in Progress state
- Using MintSteps.START_MINT_STEP as default state instead of null
- `yarn test`
- `manual testing`
> fix: Incorrect Mint Step feedback

- template/src/hooks/contracts.test.ts
- template/src/hooks/contracts.ts
Prior to wagmi 2.0 `useChain` hook was used to determine if correct chain is connected as well as to check if wallet is connected. In wagmi 2.0 the hook was replaced with useAccount and behaviour slightly changed, with a correct way to detect unconnected wallet to check for isConnected property. And `chain` will can still be returned if user haven't connected his account to the dapp
`yarn test`
`manual testing`
> fix: notConnected behaviour after moving to wagmi 2.0

- template/web/app/buy-me-coffee/_components/FormBuyCoffee.tsx
- template/web/src/components/contract-alert/ContractAlert.tsx
- template/web/src/hooks/contracts.ts
- add `ContractAlert` that will display various warning states in BuyMeACoffee app
It is inside a form right now.
- The layout / container component is not ideal. I will address in a later PR
locally
> feat: ContractAlert

- template/web/src/components/layout/guide/A.tsx
add `noopener` and `noreferrer` when opening external link
> fix: add noopener and noreferrer when opening external link

- template/web/app/paymaster-bundler/_components/GamePlay.tsx
- Paymaster Bundler experience was not resetting on logout
- Added reset
- Locally
> bug: Restart experience on logout

- template/web/src/components/layout/header/NavbarMobile.tsx
- fix mobile navigation
locally with chrome devices rendering. Tested on `iPhone SE` and `Pixel 7`
> fix: mobile navigation

- template/web/README.md
`forget build` -> `forge build`
> Fix command typo in web readme

- .changeset/rare-shirts-flow.md
- template/web/app/paymaster-bundler/_components/PaymasterBundlerDemo.tsx
- template/web/src/utils/paymasterClient.ts
Update PaymasterURL from `NEXT_PRIVATE_PAYMASTER_URL` to `NEXT_PUBLIC_PAYMASTER_URL`.
- There were two issues here. First, we are accessing this environment variable on the client side, in Nextjs applications environment variables with the `NEXT_PRIVATE` prefix are not available. Therefore we were returning `undefined`. The second issue was that our production paymaster url was incorrect, and was actually a Base paymaster url rather than the intended CDP paymaster url. 
- Updated the `transactionID` to `callID`. This is a different ID that we were mistakingly calling the transaction id. It's the call id, which is what CallStatus uses the call id to fetch and display the status of a writeContracts call.
Tested locally and in dev:
Confirmed that we are using the CDP …
> fix: Update Paymaster URL environment variable. 
